### ISSUE TITLE
Unable to generate code flow using Control Flow Visualization recipe

### ISSUE THREAD

**Issue by Jothianand** [openrewrite/rewrite-analysis#69]
Dot file is not generated while running the Control Flow Visualization recipe.

After running the recipe, it is adding the diagraph notations to the class but the dot file is not generated.

Have tried with both includeDotfile as true & false, but not generating the file. When includeDotfile is true, its adding diagraph notions and when false, it is not added.

Do we need to use a separate recipe to generate the dot file from the notations added by the recipe ?

```
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.ControlFlowVisualizationExample
displayName: Control Flow Visualization example
recipeList:
  - org.openrewrite.analysis.controlflow.ControlFlowVisualization:
      includeDotfile: true
```
